"use strict";

const TYPE_IDS = ["team", "beta"];

const TEAM_ROLES = [
  { value: "development", label: "Development / engineering" },
  { value: "art", label: "Art / UI" },
  { value: "writing", label: "Writing / lore" },
  { value: "community", label: "Community / moderation" },
  { value: "qa", label: "QA / testing" },
  { value: "other", label: "Other" },
];

const GAME_EDITIONS = [
  { value: "anniversary", label: "Fallout 4 Anniversary Edition" },
  { value: "original", label: "Fallout 4 (original release)" },
  { value: "both", label: "Both editions" },
];

const TYPES = {
  team: {
    id: "team",
    label: "Team application",
    navLabel: "Join the team",
    title: "Join the Commonwealth Online team",
    kicker: "Team",
    description:
      "Help build dedicated servers, player sync, UI, writing or community support. Tell us what you can contribute and how to reach you.",
    submitLabel: "Submit team application",
    fields: [
      {
        key: "displayName",
        label: "Display name",
        type: "text",
        required: true,
        min: 2,
        max: 80,
        autocomplete: "nickname",
        help: "How the team should refer to you.",
      },
      {
        key: "email",
        label: "Email",
        type: "email",
        required: true,
        max: 254,
        autocomplete: "email",
        help: "Used to send application updates and, if you are accepted, onboarding mail.",
      },
      {
        key: "discordHandle",
        label: "Discord username",
        type: "text",
        required: true,
        min: 2,
        max: 64,
        autocomplete: "off",
        help: "Enter your Discord username, not your server display name. We check it against the community server.",
      },
      {
        key: "timezone",
        label: "Timezone",
        type: "text",
        required: false,
        max: 64,
        autocomplete: "off",
        help: "e.g. Pacific Time, UTC+12. Helps when scheduling work sessions.",
      },
      {
        key: "role",
        label: "What would you like to help with?",
        type: "select",
        required: true,
        options: TEAM_ROLES,
      },
      {
        key: "roleOther",
        label: "If other, what would you like to do?",
        type: "text",
        required: false,
        max: 200,
        help: "Only needed if you chose Other above.",
      },
      {
        key: "portfolioUrl",
        label: "Portfolio or links",
        type: "url",
        required: false,
        max: 500,
        autocomplete: "url",
        help: "GitHub, ArtStation, a document — anything that shows your work.",
      },
      {
        key: "experience",
        label: "Relevant experience",
        type: "textarea",
        required: true,
        min: 20,
        max: 2000,
        rows: 6,
        help: "Modding, engineering, art, QA, hosting, community work — whatever applies.",
      },
      {
        key: "availability",
        label: "Availability",
        type: "textarea",
        required: false,
        max: 500,
        rows: 3,
        help: "Roughly when you can contribute, and how many hours a week.",
      },
      {
        key: "motivation",
        label: "Why do you want to join?",
        type: "textarea",
        required: true,
        min: 20,
        max: 4000,
        rows: 7,
        help: "What you want to work on and why Commonwealth Online.",
      },
      {
        key: "ageConfirmed",
        label: "I confirm I am 16 or older.",
        type: "checkbox",
        required: true,
      },
    ],
  },
  beta: {
    id: "beta",
    label: "Beta tester application",
    navLabel: "Become a beta tester",
    title: "Apply as a Commonwealth Online beta tester",
    kicker: "Playtest",
    description:
      "Help us find bugs, break builds and report what actually happens in multiplayer sessions. Testers need Fallout 4, Discord, practical mod-installation experience, and time to write useful reports.",
    submitLabel: "Submit tester application",
    fields: [
      {
        key: "displayName",
        label: "Display name",
        type: "text",
        required: true,
        min: 2,
        max: 80,
        autocomplete: "nickname",
        help: "How we should refer to you.",
      },
      {
        key: "email",
        label: "Email",
        type: "email",
        required: true,
        max: 254,
        autocomplete: "email",
        help: "Used to send tester updates, build notices and related mail.",
      },
      {
        key: "discordHandle",
        label: "Discord username",
        type: "text",
        required: true,
        min: 2,
        max: 64,
        autocomplete: "off",
        help: "Enter your Discord username, not your server display name. We check it against the community server.",
      },
      {
        key: "timezone",
        label: "Timezone",
        type: "text",
        required: false,
        max: 64,
        autocomplete: "off",
        help: "e.g. Pacific Time, UTC+12. Helps when scheduling sessions.",
      },
      {
        key: "gameEdition",
        label: "Which Fallout 4 edition can you run?",
        type: "select",
        required: true,
        options: GAME_EDITIONS,
      },
      {
        key: "manualModInstallConfirmed",
        label: "I have installed Fallout 4 mods manually and can follow manual installation instructions.",
        type: "checkbox",
        required: true,
      },
      {
        key: "modManagerConfirmed",
        label: "I have installed and managed Fallout 4 mods with a mod manager.",
        type: "checkbox",
        required: true,
      },
      {
        key: "logTroubleshootingConfirmed",
        label: "I know where to find Fallout 4 and F4SE logs and can use them to investigate problems.",
        type: "checkbox",
        required: true,
      },
      {
        key: "hardware",
        label: "Hardware notes",
        type: "textarea",
        required: false,
        max: 1000,
        rows: 3,
        help: "Optional. GPU, CPU, or anything that might affect how the game runs.",
      },
      {
        key: "experience",
        label: "Modding and troubleshooting experience",
        type: "textarea",
        required: true,
        min: 80,
        max: 2000,
        rows: 6,
        help: "Describe your manual and mod-manager installs, which manager you use, and an example of using Fallout 4 or F4SE logs to investigate an issue.",
      },
      {
        key: "availability",
        label: "Availability",
        type: "textarea",
        required: true,
        min: 10,
        max: 500,
        rows: 3,
        help: "When you can join playtests, and how often.",
      },
      {
        key: "motivation",
        label: "Why do you want to test?",
        type: "textarea",
        required: true,
        min: 20,
        max: 4000,
        rows: 6,
        help: "What you can contribute as a tester — bug reports, edge cases, regular sessions.",
      },
      {
        key: "confidentialAgreed",
        label:
          "I will keep unreleased builds, bugs and playtest details private until the team says otherwise.",
        type: "checkbox",
        required: true,
      },
      {
        key: "feedbackAgreed",
        label: "I will write useful bug reports and feedback rather than only playing the sessions.",
        type: "checkbox",
        required: true,
      },
      {
        key: "ageConfirmed",
        label: "I confirm I am 16 or older.",
        type: "checkbox",
        required: true,
      },
    ],
  },
};

const getType = (id) => TYPES[id] || null;

module.exports = { TYPES, TYPE_IDS, TEAM_ROLES, GAME_EDITIONS, getType };
